apiVersion: v1
kind: Service
metadata:
  name: agenda-pessoa
spec:
  selector:
    app: agenda-pessoa
  ports:
  - protocol: "TCP"
    port: 8082
    targetPort: 8082
    nodePort: 30002
  type: LoadBalancer
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-pessoa
spec:
  selector:
    matchLabels:
      app: agenda-pessoa
  replicas: 2
  template:
    metadata:
      labels:
        app: agenda-pessoa
    spec:      
      containers:
        - name: agenda-pessoa
          image: italoherbert/agenda-pessoa
          imagePullPolicy: IfNotPresent          
          envFrom:
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: agenda-kafka-config
          env:
            - name: POSTGRES_URL
              value: jdbc:postgresql://10.103.165.181:5432/agenda            
          ports:        
            - containerPort: 8082        