apiVersion: v1
kind: Service
metadata:
  name: agenda-pessoa
spec:
  selector:
    app: agenda-pessoa
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-pessoa
spec:
  selector:
    matchLabels:
      app: agenda-pessoa
  replicas: 2
  template:
    metadata:
      labels:
        app: agenda-pessoa
    spec:
      containers:
        - name: agenda-pessoa
          image: italoherbert/agenda-pessoa
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:        
            - containerPort: 8080
        - name: postgresql
          image: postgres
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: postgresql-pvc