apiVersion: v1
kind: PersistentVolume
metadata:
  name: agenda-pessoa-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/agenda/pessoa-data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agenda-pessoa-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi