apiVersion: v1
kind: Service
metadata:
  name: agenda-log
spec:
  selector:
    app: agenda-log
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
    nodePort: 30001
  type: LoadBalancer
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-log
spec:
  selector:
    matchLabels:
      app: agenda-log
  replicas: 2
  template:
    metadata:
      labels:
        app: agenda-log
    spec:
      containers:
        - name: agenda-log
          image: italoherbert/agenda-log
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: agenda-kafka-config 
          ports:        
            - containerPort: 8081        