apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080
      name: http
      protocol : TCP
      nodePort: 30080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins  
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
      containers:        
        - image: jenkins/jenkins:jdk17-preview
          name: jenkins  
          securityContext:
            privileged: true        
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-volume
              mountPath: /var/jenkins_home 
            - name: docker-sock-volume
              mountPath: /var/run/docker.sock          
      volumes:
        - name: jenkins-volume
          emptyDir : {}
        - name: docker-sock-volume
          hostPath:
            path: /var/run/docker.sock