apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  labels:
    app: zookeeper
data:
  ZOOKEEPER_SERVER_ID: "1"
  ZOOKEEPER_CLIENT_PORT: "2181"

#  ZOO_ENABLE_AUTH: 'yes'
#  ZOO_SERVER_USERS: zookeeper
#  ZOO_SERVER_PASSWORDS: zookeeper
#  ZOO_CLIENT_USER: agenda
#  ZOO_CLIENT_PASSWORD: agenda

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
data:
  KAFKA_ZOOKEEPER_CONNECT: localhost:2181  
  KAFKA_PORT: "29092"
    
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  KAFKA_DELETE_TOPIC_ENABLE: "true"

  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
  KAFKA_CREATE_TOPICS: 'example-topic:1:1'

# ALLOW_PLAINTEXT_LISTENER: 'yes'
# ZOOKEEPER_SASL_ENABLED: 'no'
#  KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT

#  KAFKA_ZOOKEEPER_PROTOCOL: SASL
#  KAFKA_ZOOKEEPER_USER: zookeeper
#  KAFKA_ZOOKEEPER_PASSWORD: zookeeper
   
#  KAFKA_CLIENT_USER: agenda
#  kAFKA_CLIENT_PASSWORD: agenda
      
#  KAFKA_INTER_BROKER_USER: italo
#  KAFKA_INTER_BROKER_PASSWORD: italo

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: external
      port: 9092
      targetPort: 9092
      nodePort: 30092

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka 
  serviceName: kafka 
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 0
      containers:    
        - name: zookeeper
          image: zookeeper
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: zookeeper-config
          ports:
            - containerPort: 2181
        - name: kafka
          image: wurstmeister/kafka
          imagePullPolicy: Always
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP            
            - name: KAFKA_LISTENERS
              value: INTERNAL://:29092,EXTERNAL://$(KAFKA_ADVERTISED_HOST_NAME):9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://127.0.0.1:29092,EXTERNAL://$(KAFKA_ADVERTISED_HOST_NAME):9092
            - name: KAFKA_INTER_BROKER_LISTENER_NAME 
              value: INTERNAL
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - containerPort: 29092
            - containerPort: 9092