apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - port: 9092
      name: http
      protocol : TCP
      nodePort: 30100
      targetPort: 9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka  
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 0
      containers:    
        - name: zookeeper
          image: zookeeper
          ports:
            - 2181:2181
        - name: kafka
          image: bitnami/kafka
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: localhost
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: 1
            - name: KAFKA_CREATE_TOPICS
              value: example-topic:1:1
          ports:
            - 9092:9092