apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  labels:
    app: zookeeper
data:
  ZOOKEEPER_SERVER_ID: "1"
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_DATA_DIR: "/var/lib/zookeeper/data"
  ZOOKEEPER_LOG_DIR: "/var/lib/zookeeper/log"

#  ZOO_ENABLE_AUTH: 'yes'
#  ZOO_SERVER_USERS: zookeeper
#  ZOO_SERVER_PASSWORDS: zookeeper
#  ZOO_CLIENT_USER: agenda
#  ZOO_CLIENT_PASSWORD: agenda

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
data:
  ALLOW_PLAINTEXT_LISTENER: 'yes'
  ZOOKEEPER_SASL_ENABLED: 'no'

  KAFKA_ZOOKEEPER_CONNECT: 0.0.0.0:2181
  KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,   
  KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
  KAFKA_PORT: "30092"
  
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
  KAFKA_CREATE_TOPICS: 'example-topic:1:1'

#  KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT

#  KAFKA_ZOOKEEPER_PROTOCOL: SASL
#  KAFKA_ZOOKEEPER_USER: zookeeper
#  KAFKA_ZOOKEEPER_PASSWORD: zookeeper
   
#  KAFKA_CLIENT_USER: agenda
#  kAFKA_CLIENT_PASSWORD: agenda
      
#  KAFKA_INTER_BROKER_USER: italo
#  KAFKA_INTER_BROKER_PASSWORD: italo

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: external
      port: 30092
      targetPort: 9092
      nodePort: 30092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka  
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 0
      containers:    
        - name: zookeeper
          image: zookeeper
          envFrom:
            - configMapRef:
                name: zookeeper-config
          ports:
            - containerPort: 2181
        - name: kafka
          image: wurstmeister/kafka
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - containerPort: 29092
            - containerPort: 9092