apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  labels:
    app: zookeeper
data:
  ZOO_ENABLE_AUTH: 'yes'
  ZOO_SERVER_USERS: zookeeper
  ZOO_SERVER_PASSWORDS: zookeeper
  ZOO_CLIENT_USER: agenda
  ZOO_CLIENT_PASSWORD: agenda

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
data:
  ALLOW_PLAINTEXT_LISTENER: 'no'
  KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_CFG_LISTENERS: INTERNAL://:9092,CLIENT://:9093,   
  KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,CLIENT://localhost:9093
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
  KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  
  KAFKA_ZOOKEEPER_PROTOCOL: SASL
  KAFKA_ZOOKEEPER_USER: zookeeper
  KAFKA_ZOOKEEPER_PASSWORD: zookeeper
   
  KAFKA_CLIENT_USER: agenda
  kAFKA_CLIENT_PASSWORD: agenda
      
  KAFKA_INTER_BROKER_USER: italo
  KAFKA_INTER_BROKER_PASSWORD: italo

  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
  KAFKA_CREATE_TOPICS: 'example-top/ic:1:1'

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: external
      port: 30092
      targetPort: 9092
      nodePort: 30092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka  
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 0
      containers:    
        - name: zookeeper
          image: zookeeper
          envFrom:
            - configMapRef:
                name: zookeeper-config
          ports:
            - containerPort: 2181
        - name: kafka
          image: bitnami/kafka
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - containerPort: 9092