apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  
  
---

apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  type: NodePort
  selector:
    app: postgresql-service
  ports:
  - protocol: "TCP"
    port: 5432
    targetPort: 5432
    nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-server
spec:
  selector:
    matchLabels:
      app: postgresql-server
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-server
    spec:
      containers:
        - name: postgresql-server-container
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: postgresql-pvc