
spring:
  application:
    name: agenda-pessoa
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      auto-commit: false   
  jpa: 
    hibernate:            
      ddl-auto: update    
    generate-ddl: true
    show-sql: true
  
  kafka:       
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  
app:
  kafka:
    producer:
      topic: example-topic
    
server:  port: 8082      